package zombiedefense;

import static javax.swing.JFrame.setDefaultLookAndFeelDecorated;
import javax.swing.UIManager;
import static zombiedefense.VentanaPrincipal.ventana;

public class VentanaConfiguracion extends javax.swing.JFrame {
    
    public VentanaConfiguracion() {
        try {
            setDefaultLookAndFeelDecorated(true);
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCompleto = new javax.swing.JPanel();
        mapas = new javax.swing.JTabbedPane();
        mapaInferno = new javax.swing.JPanel();
        imagenMapa1 = new javax.swing.JLabel();
        eMapa1 = new javax.swing.JToggleButton();
        mapaTierra = new javax.swing.JPanel();
        imagenMapa2 = new javax.swing.JLabel();
        eMapa2 = new javax.swing.JToggleButton();
        mapaMistico = new javax.swing.JPanel();
        imagenMapa3 = new javax.swing.JLabel();
        eMapa3 = new javax.swing.JToggleButton();
        infoPersonajes = new javax.swing.JTabbedPane();
        P1 = new javax.swing.JPanel();
        iconP1 = new javax.swing.JLabel();
        atackP1 = new javax.swing.JLabel();
        armaP1 = new javax.swing.JLabel();
        habP1 = new javax.swing.JLabel();
        apP1 = new javax.swing.JLabel();
        auP1 = new javax.swing.JLabel();
        arP1 = new javax.swing.JLabel();
        habilidadesP1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        nombreP1 = new javax.swing.JLabel();
        nameP1 = new javax.swing.JLabel();
        P2 = new javax.swing.JPanel();
        iconP2 = new javax.swing.JLabel();
        atackP2 = new javax.swing.JLabel();
        armaP2 = new javax.swing.JLabel();
        habP2 = new javax.swing.JLabel();
        auP2 = new javax.swing.JLabel();
        apP2 = new javax.swing.JLabel();
        arP2 = new javax.swing.JLabel();
        habilidadesP2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        nombreP2 = new javax.swing.JLabel();
        nameP2 = new javax.swing.JLabel();
        P3 = new javax.swing.JPanel();
        iconP3 = new javax.swing.JLabel();
        atackP3 = new javax.swing.JLabel();
        armaP3 = new javax.swing.JLabel();
        habP3 = new javax.swing.JLabel();
        auP3 = new javax.swing.JLabel();
        apP3 = new javax.swing.JLabel();
        arP3 = new javax.swing.JLabel();
        habilidadesP3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        nombreP3 = new javax.swing.JLabel();
        nameP3 = new javax.swing.JLabel();
        P4 = new javax.swing.JPanel();
        iconP4 = new javax.swing.JLabel();
        atackP4 = new javax.swing.JLabel();
        armaP4 = new javax.swing.JLabel();
        habP4 = new javax.swing.JLabel();
        auP4 = new javax.swing.JLabel();
        apP4 = new javax.swing.JLabel();
        arP4 = new javax.swing.JLabel();
        habilidadesP4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        nombreP4 = new javax.swing.JLabel();
        nameP4 = new javax.swing.JLabel();
        P5 = new javax.swing.JPanel();
        iconP5 = new javax.swing.JLabel();
        atackP5 = new javax.swing.JLabel();
        armaP5 = new javax.swing.JLabel();
        habP5 = new javax.swing.JLabel();
        auP5 = new javax.swing.JLabel();
        apP5 = new javax.swing.JLabel();
        arP5 = new javax.swing.JLabel();
        habilidadesP5 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        nombreP5 = new javax.swing.JLabel();
        nameP5 = new javax.swing.JLabel();
        P6 = new javax.swing.JPanel();
        iconP6 = new javax.swing.JLabel();
        atackP6 = new javax.swing.JLabel();
        armaP6 = new javax.swing.JLabel();
        habP6 = new javax.swing.JLabel();
        auP6 = new javax.swing.JLabel();
        apP6 = new javax.swing.JLabel();
        arP6 = new javax.swing.JLabel();
        habilidadesP6 = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList<>();
        nombreP6 = new javax.swing.JLabel();
        nameP6 = new javax.swing.JLabel();
        panelEscoger = new javax.swing.JPanel();
        vampiroEs = new javax.swing.JCheckBox();
        astroEs = new javax.swing.JCheckBox();
        ninjaEs = new javax.swing.JCheckBox();
        caballeroEs = new javax.swing.JCheckBox();
        arqueroEs = new javax.swing.JCheckBox();
        esqueletoEs = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        panelCompleto.setBackground(new java.awt.Color(0, 51, 0));

        mapas.setBackground(new java.awt.Color(0, 51, 0));
        mapas.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 30, 0)));
        mapas.setForeground(new java.awt.Color(255, 255, 255));

        mapaInferno.setBackground(new java.awt.Color(0, 51, 0));
        mapaInferno.setForeground(new java.awt.Color(255, 255, 255));

        imagenMapa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mapa1.jpg"))); // NOI18N

        eMapa1.setText("Elegir mapa");

        javax.swing.GroupLayout mapaInfernoLayout = new javax.swing.GroupLayout(mapaInferno);
        mapaInferno.setLayout(mapaInfernoLayout);
        mapaInfernoLayout.setHorizontalGroup(
            mapaInfernoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapaInfernoLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(imagenMapa1)
                .addGap(52, 52, 52))
            .addGroup(mapaInfernoLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(eMapa1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mapaInfernoLayout.setVerticalGroup(
            mapaInfernoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mapaInfernoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(imagenMapa1)
                .addGap(18, 18, 18)
                .addComponent(eMapa1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        mapas.addTab("Mapa infierno", mapaInferno);

        mapaTierra.setBackground(new java.awt.Color(0, 51, 0));
        mapaTierra.setForeground(new java.awt.Color(255, 255, 255));

        imagenMapa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mapa2.png"))); // NOI18N

        eMapa2.setText("Elegir mapa");

        javax.swing.GroupLayout mapaTierraLayout = new javax.swing.GroupLayout(mapaTierra);
        mapaTierra.setLayout(mapaTierraLayout);
        mapaTierraLayout.setHorizontalGroup(
            mapaTierraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapaTierraLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(imagenMapa2)
                .addGap(52, 52, 52))
            .addGroup(mapaTierraLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(eMapa2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mapaTierraLayout.setVerticalGroup(
            mapaTierraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mapaTierraLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(imagenMapa2)
                .addGap(18, 18, 18)
                .addComponent(eMapa2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        mapas.addTab("Mapa tierra", mapaTierra);

        mapaMistico.setBackground(new java.awt.Color(0, 51, 0));
        mapaMistico.setForeground(new java.awt.Color(255, 255, 255));

        imagenMapa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mapa3.jpg"))); // NOI18N

        eMapa3.setText("Elegir mapa");

        javax.swing.GroupLayout mapaMisticoLayout = new javax.swing.GroupLayout(mapaMistico);
        mapaMistico.setLayout(mapaMisticoLayout);
        mapaMisticoLayout.setHorizontalGroup(
            mapaMisticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapaMisticoLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(imagenMapa3)
                .addGap(52, 52, 52))
            .addGroup(mapaMisticoLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(eMapa3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mapaMisticoLayout.setVerticalGroup(
            mapaMisticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mapaMisticoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(imagenMapa3)
                .addGap(18, 18, 18)
                .addComponent(eMapa3)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        mapas.addTab("Mapa mistico", mapaMistico);

        infoPersonajes.setBackground(new java.awt.Color(0, 51, 0));
        infoPersonajes.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 30, 0)));
        infoPersonajes.setForeground(new java.awt.Color(255, 255, 255));
        infoPersonajes.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        infoPersonajes.setPreferredSize(new java.awt.Dimension(100, 192));

        P1.setBackground(new java.awt.Color(0, 51, 0));
        P1.setForeground(new java.awt.Color(255, 255, 255));

        iconP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vampiro.png"))); // NOI18N

        atackP1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        atackP1.setText("Ataque:");

        armaP1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        armaP1.setText("Arma: ");

        habP1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        habP1.setText("Habilidades:");

        apP1.setText("30 P");

        auP1.setText("+5 cada 2 niv.");

        arP1.setText("Espada de acero");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Saltar Obstaculos        - Nivel 1", "Cerrar Spawning\t         - Nivel 5", "Regeneracion              - Nivel 15" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionBackground(new java.awt.Color(0, 30, 0));
        habilidadesP1.setViewportView(jList1);

        nombreP1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nombreP1.setText("Nombre:");

        nameP1.setText("Vampiro");

        javax.swing.GroupLayout P1Layout = new javax.swing.GroupLayout(P1);
        P1.setLayout(P1Layout);
        P1Layout.setHorizontalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(iconP1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P1Layout.createSequentialGroup()
                                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(atackP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(armaP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(arP1)
                                    .addGroup(P1Layout.createSequentialGroup()
                                        .addComponent(apP1)
                                        .addGap(18, 18, 18)
                                        .addComponent(auP1))))
                            .addGroup(P1Layout.createSequentialGroup()
                                .addComponent(nombreP1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameP1))))
                    .addGroup(P1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(habP1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(habilidadesP1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, Short.MAX_VALUE))
        );
        P1Layout.setVerticalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(P1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconP1))
                    .addGroup(P1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreP1)
                            .addComponent(nameP1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atackP1)
                            .addComponent(apP1)
                            .addComponent(auP1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(armaP1)
                            .addComponent(arP1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(habP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(habilidadesP1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        infoPersonajes.addTab("Personaje 1", P1);

        P2.setBackground(new java.awt.Color(0, 51, 0));
        P2.setForeground(new java.awt.Color(255, 255, 255));

        iconP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/esqueleto.png"))); // NOI18N

        atackP2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        atackP2.setText("Ataque:");

        armaP2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        armaP2.setText("Arma: ");

        habP2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        habP2.setText("Habilidades:");

        auP2.setText("+5 cada 2 niv.");

        apP2.setText("30 P");

        arP2.setText("Espada de plata");

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Doble ataque cercano        - Nivel 1", "Doble experiencia               - Nivel 5", "Inmortalidad                        - Nivel 20" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.setSelectionBackground(new java.awt.Color(0, 30, 0));
        habilidadesP2.setViewportView(jList2);

        nombreP2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nombreP2.setText("Nombre:");

        nameP2.setText("Esqueleto");

        javax.swing.GroupLayout P2Layout = new javax.swing.GroupLayout(P2);
        P2.setLayout(P2Layout);
        P2Layout.setHorizontalGroup(
            P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P2Layout.createSequentialGroup()
                .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(iconP2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P2Layout.createSequentialGroup()
                                .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(atackP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(armaP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(arP2)
                                    .addGroup(P2Layout.createSequentialGroup()
                                        .addComponent(apP2)
                                        .addGap(18, 18, 18)
                                        .addComponent(auP2))))
                            .addGroup(P2Layout.createSequentialGroup()
                                .addComponent(nombreP2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameP2))))
                    .addGroup(P2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(habP2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(habilidadesP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, Short.MAX_VALUE))
        );
        P2Layout.setVerticalGroup(
            P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P2Layout.createSequentialGroup()
                .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(P2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconP2))
                    .addGroup(P2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreP2)
                            .addComponent(nameP2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atackP2)
                            .addComponent(apP2)
                            .addComponent(auP2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(armaP2)
                            .addComponent(arP2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(habP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(habilidadesP2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        infoPersonajes.addTab("Personaje 2", P2);

        P3.setBackground(new java.awt.Color(0, 51, 0));
        P3.setForeground(new java.awt.Color(255, 255, 255));

        iconP3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arquero.png"))); // NOI18N

        atackP3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        atackP3.setText("Ataque:");

        armaP3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        armaP3.setText("Arma: ");

        habP3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        habP3.setText("Habilidades:");

        auP3.setText("+5 cada 2 niv.");

        apP3.setText("20 P");

        arP3.setText("Arco y Flecha");

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Doble vida                         - Nivel 1", "Doble Ataque lejanos      - Nivel 5", "Mayor alcance maximo  - Nivel 15" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList3.setSelectionBackground(new java.awt.Color(0, 30, 0));
        habilidadesP3.setViewportView(jList3);

        nombreP3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nombreP3.setText("Nombre:");

        nameP3.setText("Arquero");

        javax.swing.GroupLayout P3Layout = new javax.swing.GroupLayout(P3);
        P3.setLayout(P3Layout);
        P3Layout.setHorizontalGroup(
            P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P3Layout.createSequentialGroup()
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(iconP3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P3Layout.createSequentialGroup()
                                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(atackP3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(armaP3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(arP3)
                                    .addGroup(P3Layout.createSequentialGroup()
                                        .addComponent(apP3)
                                        .addGap(18, 18, 18)
                                        .addComponent(auP3))))
                            .addGroup(P3Layout.createSequentialGroup()
                                .addComponent(nombreP3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameP3))))
                    .addGroup(P3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(habP3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(habilidadesP3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, Short.MAX_VALUE))
        );
        P3Layout.setVerticalGroup(
            P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P3Layout.createSequentialGroup()
                .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(P3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconP3))
                    .addGroup(P3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreP3)
                            .addComponent(nameP3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atackP3)
                            .addComponent(apP3)
                            .addComponent(auP3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(armaP3)
                            .addComponent(arP3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(habP3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(habilidadesP3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        infoPersonajes.addTab("Personaje 3", P3);

        P4.setBackground(new java.awt.Color(0, 51, 0));
        P4.setForeground(new java.awt.Color(255, 255, 255));

        iconP4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/caballero.png"))); // NOI18N

        atackP4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        atackP4.setText("Ataque:");

        armaP4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        armaP4.setText("Arma: ");

        habP4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        habP4.setText("Habilidades:");

        auP4.setText("+5 cada 2 niv.");

        apP4.setText("30 P");

        arP4.setText("Espada de acero");

        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Saltar Obstaculos            - Nivel 1", "Doble ataque cercano    - Nivel 5", "Doble vida                        - Nivel 15" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList4.setSelectionBackground(new java.awt.Color(0, 30, 0));
        habilidadesP4.setViewportView(jList4);

        nombreP4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nombreP4.setText("Nombre:");

        nameP4.setText("Caballero");

        javax.swing.GroupLayout P4Layout = new javax.swing.GroupLayout(P4);
        P4.setLayout(P4Layout);
        P4Layout.setHorizontalGroup(
            P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P4Layout.createSequentialGroup()
                .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(iconP4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P4Layout.createSequentialGroup()
                                .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(atackP4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(armaP4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(arP4)
                                    .addGroup(P4Layout.createSequentialGroup()
                                        .addComponent(apP4)
                                        .addGap(18, 18, 18)
                                        .addComponent(auP4))))
                            .addGroup(P4Layout.createSequentialGroup()
                                .addComponent(nombreP4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameP4))))
                    .addGroup(P4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(habP4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(habilidadesP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, Short.MAX_VALUE))
        );
        P4Layout.setVerticalGroup(
            P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P4Layout.createSequentialGroup()
                .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(P4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconP4))
                    .addGroup(P4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreP4)
                            .addComponent(nameP4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atackP4)
                            .addComponent(apP4)
                            .addComponent(auP4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(armaP4)
                            .addComponent(arP4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(habP4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(habilidadesP4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        infoPersonajes.addTab("Personaje 4", P4);

        P5.setBackground(new java.awt.Color(0, 51, 0));
        P5.setForeground(new java.awt.Color(255, 255, 255));

        iconP5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/astro.png"))); // NOI18N

        atackP5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        atackP5.setText("Ataque:");

        armaP5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        armaP5.setText("Arma: ");

        habP5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        habP5.setText("Habilidades:");

        auP5.setText("+5 cada 2 niv.");

        apP5.setText("40 P");

        arP5.setText("Espada laser");

        jList5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Doble Experiencia           - Nivel 1", "Doble ataque cercano    - Nivel 5", "Doble vida                       - Nivel 15" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList5.setSelectionBackground(new java.awt.Color(0, 30, 0));
        habilidadesP5.setViewportView(jList5);

        nombreP5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nombreP5.setText("Nombre:");

        nameP5.setText("Astro");

        javax.swing.GroupLayout P5Layout = new javax.swing.GroupLayout(P5);
        P5.setLayout(P5Layout);
        P5Layout.setHorizontalGroup(
            P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P5Layout.createSequentialGroup()
                .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P5Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(iconP5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P5Layout.createSequentialGroup()
                                .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(atackP5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(armaP5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(arP5)
                                    .addGroup(P5Layout.createSequentialGroup()
                                        .addComponent(apP5)
                                        .addGap(18, 18, 18)
                                        .addComponent(auP5))))
                            .addGroup(P5Layout.createSequentialGroup()
                                .addComponent(nombreP5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameP5))))
                    .addGroup(P5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(habP5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(habilidadesP5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, Short.MAX_VALUE))
        );
        P5Layout.setVerticalGroup(
            P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P5Layout.createSequentialGroup()
                .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(P5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconP5))
                    .addGroup(P5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreP5)
                            .addComponent(nameP5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atackP5)
                            .addComponent(apP5)
                            .addComponent(auP5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(armaP5)
                            .addComponent(arP5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(habP5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(habilidadesP5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        infoPersonajes.addTab("Personaje 5", P5);

        P6.setBackground(new java.awt.Color(0, 51, 0));
        P6.setForeground(new java.awt.Color(255, 255, 255));

        iconP6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ninja.png"))); // NOI18N

        atackP6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        atackP6.setText("Ataque:");

        armaP6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        armaP6.setText("Arma: ");

        habP6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        habP6.setText("Habilidades:");

        auP6.setText("+5 cada 2 niv.");

        apP6.setText("20 P");

        arP6.setText("Kunai");

        jList6.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Saltar Obstaculos        - Nivel 1", "Doble experiencia       - Nivel 5", "Sin ruidos                     - Nivel 15" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList6.setSelectionBackground(new java.awt.Color(0, 30, 0));
        habilidadesP6.setViewportView(jList6);

        nombreP6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nombreP6.setText("Nombre:");

        nameP6.setText("Ninja");

        javax.swing.GroupLayout P6Layout = new javax.swing.GroupLayout(P6);
        P6.setLayout(P6Layout);
        P6Layout.setHorizontalGroup(
            P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P6Layout.createSequentialGroup()
                .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(iconP6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P6Layout.createSequentialGroup()
                                .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(atackP6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(armaP6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(arP6)
                                    .addGroup(P6Layout.createSequentialGroup()
                                        .addComponent(apP6)
                                        .addGap(18, 18, 18)
                                        .addComponent(auP6))))
                            .addGroup(P6Layout.createSequentialGroup()
                                .addComponent(nombreP6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameP6))))
                    .addGroup(P6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(habP6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(habilidadesP6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, Short.MAX_VALUE))
        );
        P6Layout.setVerticalGroup(
            P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P6Layout.createSequentialGroup()
                .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(P6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconP6))
                    .addGroup(P6Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreP6)
                            .addComponent(nameP6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atackP6)
                            .addComponent(apP6)
                            .addComponent(auP6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(armaP6)
                            .addComponent(arP6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(habP6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(habilidadesP6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        infoPersonajes.addTab("Personaje 6", P6);

        panelEscoger.setBackground(new java.awt.Color(0, 51, 0));
        panelEscoger.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 30, 0)));

        vampiroEs.setForeground(null);
        vampiroEs.setText("Vampiro");

        astroEs.setForeground(null);
        astroEs.setText("Astro");

        ninjaEs.setForeground(null);
        ninjaEs.setText("Ninja");

        caballeroEs.setForeground(null);
        caballeroEs.setText("Caballero");

        arqueroEs.setForeground(null);
        arqueroEs.setText("Arquero");

        esqueletoEs.setForeground(null);
        esqueletoEs.setText("Esqueleto");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(null);
        jLabel1.setText("Elija sus personajes");

        javax.swing.GroupLayout panelEscogerLayout = new javax.swing.GroupLayout(panelEscoger);
        panelEscoger.setLayout(panelEscogerLayout);
        panelEscogerLayout.setHorizontalGroup(
            panelEscogerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEscogerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEscogerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(esqueletoEs)
                    .addComponent(arqueroEs)
                    .addComponent(caballeroEs)
                    .addComponent(ninjaEs)
                    .addComponent(astroEs)
                    .addComponent(vampiroEs)
                    .addComponent(jLabel1))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelEscogerLayout.setVerticalGroup(
            panelEscogerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEscogerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(vampiroEs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(astroEs)
                .addGap(12, 12, 12)
                .addComponent(ninjaEs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(caballeroEs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(arqueroEs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(esqueletoEs)
                .addGap(24, 24, 24))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ventana de Configuraciones");

        jButton1.setBackground(new java.awt.Color(0, 51, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir al menu");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCompletoLayout = new javax.swing.GroupLayout(panelCompleto);
        panelCompleto.setLayout(panelCompletoLayout);
        panelCompletoLayout.setHorizontalGroup(
            panelCompletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompletoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(panelEscoger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(infoPersonajes, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mapas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCompletoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(522, 522, 522))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCompletoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(411, 411, 411))
        );
        panelCompletoLayout.setVerticalGroup(
            panelCompletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCompletoLayout.createSequentialGroup()
                .addGroup(panelCompletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCompletoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGroup(panelCompletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCompletoLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(mapas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCompletoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(infoPersonajes, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))))
                    .addGroup(panelCompletoLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(panelEscoger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        getContentPane().add(panelCompleto);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P1;
    private javax.swing.JPanel P2;
    private javax.swing.JPanel P3;
    private javax.swing.JPanel P4;
    private javax.swing.JPanel P5;
    private javax.swing.JPanel P6;
    private javax.swing.JLabel apP1;
    private javax.swing.JLabel apP2;
    private javax.swing.JLabel apP3;
    private javax.swing.JLabel apP4;
    private javax.swing.JLabel apP5;
    private javax.swing.JLabel apP6;
    private javax.swing.JLabel arP1;
    private javax.swing.JLabel arP2;
    private javax.swing.JLabel arP3;
    private javax.swing.JLabel arP4;
    private javax.swing.JLabel arP5;
    private javax.swing.JLabel arP6;
    private javax.swing.JLabel armaP1;
    private javax.swing.JLabel armaP2;
    private javax.swing.JLabel armaP3;
    private javax.swing.JLabel armaP4;
    private javax.swing.JLabel armaP5;
    private javax.swing.JLabel armaP6;
    private javax.swing.JCheckBox arqueroEs;
    private javax.swing.JCheckBox astroEs;
    private javax.swing.JLabel atackP1;
    private javax.swing.JLabel atackP2;
    private javax.swing.JLabel atackP3;
    private javax.swing.JLabel atackP4;
    private javax.swing.JLabel atackP5;
    private javax.swing.JLabel atackP6;
    private javax.swing.JLabel auP1;
    private javax.swing.JLabel auP2;
    private javax.swing.JLabel auP3;
    private javax.swing.JLabel auP4;
    private javax.swing.JLabel auP5;
    private javax.swing.JLabel auP6;
    private javax.swing.JCheckBox caballeroEs;
    private javax.swing.JToggleButton eMapa1;
    private javax.swing.JToggleButton eMapa2;
    private javax.swing.JToggleButton eMapa3;
    private javax.swing.JCheckBox esqueletoEs;
    private javax.swing.JLabel habP1;
    private javax.swing.JLabel habP2;
    private javax.swing.JLabel habP3;
    private javax.swing.JLabel habP4;
    private javax.swing.JLabel habP5;
    private javax.swing.JLabel habP6;
    private javax.swing.JScrollPane habilidadesP1;
    private javax.swing.JScrollPane habilidadesP2;
    private javax.swing.JScrollPane habilidadesP3;
    private javax.swing.JScrollPane habilidadesP4;
    private javax.swing.JScrollPane habilidadesP5;
    private javax.swing.JScrollPane habilidadesP6;
    private javax.swing.JLabel iconP1;
    private javax.swing.JLabel iconP2;
    private javax.swing.JLabel iconP3;
    private javax.swing.JLabel iconP4;
    private javax.swing.JLabel iconP5;
    private javax.swing.JLabel iconP6;
    private javax.swing.JLabel imagenMapa1;
    private javax.swing.JLabel imagenMapa2;
    private javax.swing.JLabel imagenMapa3;
    private javax.swing.JTabbedPane infoPersonajes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JList<String> jList6;
    private javax.swing.JPanel mapaInferno;
    private javax.swing.JPanel mapaMistico;
    private javax.swing.JPanel mapaTierra;
    private javax.swing.JTabbedPane mapas;
    private javax.swing.JLabel nameP1;
    private javax.swing.JLabel nameP2;
    private javax.swing.JLabel nameP3;
    private javax.swing.JLabel nameP4;
    private javax.swing.JLabel nameP5;
    private javax.swing.JLabel nameP6;
    private javax.swing.JCheckBox ninjaEs;
    private javax.swing.JLabel nombreP1;
    private javax.swing.JLabel nombreP2;
    private javax.swing.JLabel nombreP3;
    private javax.swing.JLabel nombreP4;
    private javax.swing.JLabel nombreP5;
    private javax.swing.JLabel nombreP6;
    private javax.swing.JPanel panelCompleto;
    private javax.swing.JPanel panelEscoger;
    private javax.swing.JCheckBox vampiroEs;
    // End of variables declaration//GEN-END:variables

private void asignarValores(){
    
}


}
