package zombiedefense;

import java.awt.Color;
import javax.swing.UIManager;
import zombiedefense.personaje.Personaje;

/**
 *
 * @author Danny Jimenez
 */

public class VentanaPrincipal extends javax.swing.JFrame{

    /**
     * Creates new form VentanaPrincipal
     */
    int x, y;
    public static VentanaPrincipal ventana = new VentanaPrincipal();
    public static Personaje[] personajes = {new Personaje(1), new Personaje(2), new Personaje(3)};
    int p1, p2, p3, mapa;
    public static Juego juego;
    
    
    public static void main(String[] args){
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }
    public VentanaPrincipal() {
        try {
            setDefaultLookAndFeelDecorated(true);
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instrucciones = new javax.swing.JDialog();
        intruccionesPrincipal = new javax.swing.JPanel();
        botonTitle = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        divisiones = new javax.swing.JTabbedPane();
        paneInformacion = new javax.swing.JScrollPane();
        txtInformacion = new javax.swing.JTextArea();
        paneInstrucciones = new javax.swing.JScrollPane();
        txtInstrucciones = new javax.swing.JTextArea();
        panelCompleto = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        btnConfig = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();

        instrucciones.setAlwaysOnTop(true);
        instrucciones.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        instrucciones.setUndecorated(true);
        instrucciones.setSize(new java.awt.Dimension(489, 367));

        intruccionesPrincipal.setBackground(new java.awt.Color(0, 53, 0));
        intruccionesPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        intruccionesPrincipal.setPreferredSize(new java.awt.Dimension(489, 367));

        botonTitle.setBackground(new java.awt.Color(0, 51, 0));

        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Zombie Defense - Intrucciones");
        lblTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblTituloMouseDragged(evt);
            }
        });
        lblTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTituloMousePressed(evt);
            }
        });

        btnCerrar.setBackground(new java.awt.Color(0, 35, 0));
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar");
        btnCerrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botonTitleLayout = new javax.swing.GroupLayout(botonTitle);
        botonTitle.setLayout(botonTitleLayout);
        botonTitleLayout.setHorizontalGroup(
            botonTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        botonTitleLayout.setVerticalGroup(
            botonTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(botonTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(botonTitleLayout.createSequentialGroup()
                        .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addGroup(botonTitleLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        divisiones.setBackground(new java.awt.Color(0, 51, 0));
        divisiones.setForeground(new java.awt.Color(255, 255, 255));
        divisiones.setOpaque(true);

        paneInformacion.setBackground(new java.awt.Color(0, 51, 0));
        paneInformacion.setBorder(null);
        paneInformacion.setForeground(new java.awt.Color(255, 255, 255));

        txtInformacion.setEditable(false);
        txtInformacion.setBackground(new java.awt.Color(0, 40, 0));
        txtInformacion.setColumns(20);
        txtInformacion.setForeground(new java.awt.Color(255, 255, 255));
        txtInformacion.setRows(5);
        txtInformacion.setText("Zombie defense es un juego creado para\n\nCradores: - Danny Jimenez\n                  - Luis Fernando *****\n\nVersion: 1.0 X\n\nUltima fecha de actualización: 17 - Nov - 2020\n\nNota: Este es un proyecto para el curso de Programación orientada a objetos, validado\ncomo proyecto 2 del curso, con el profesor Yuen Law.\n\nPara mayor información del proyecto revisar la documentación en el siguiente link:\n- ***Link***\n\n");
        paneInformacion.setViewportView(txtInformacion);

        divisiones.addTab("Informacion", paneInformacion);

        paneInstrucciones.setBackground(new java.awt.Color(0, 51, 0));
        paneInstrucciones.setBorder(null);
        paneInstrucciones.setForeground(new java.awt.Color(255, 255, 255));

        txtInstrucciones.setBackground(new java.awt.Color(0, 40, 0));
        txtInstrucciones.setColumns(20);
        txtInstrucciones.setForeground(new java.awt.Color(255, 255, 255));
        txtInstrucciones.setRows(5);
        txtInstrucciones.setText("En la ventana principal se tienen diferentes botones:\n- Boton Play: Con este se empezará el juego, con el personaje que hayas elegido o con \nun personaje por defecto si no lo hiciste\n- Boton Configuracion: En este se abrira otra ventana donde tendrás que elegir el \npersonaje con el que deseas jugar, tambien se podran hacer otras configuraciones \ncomo el sonido, habilitar / deshabilitar la barra de titulo de las ventanas, ***\n- Boton Salir: su unica función es cerrar el juego.\n- Boton Intrucciones: este boton abre la ventana de instrucciones e información.");
        paneInstrucciones.setViewportView(txtInstrucciones);

        divisiones.addTab("Intrucciones del juego", paneInstrucciones);

        javax.swing.GroupLayout intruccionesPrincipalLayout = new javax.swing.GroupLayout(intruccionesPrincipal);
        intruccionesPrincipal.setLayout(intruccionesPrincipalLayout);
        intruccionesPrincipalLayout.setHorizontalGroup(
            intruccionesPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(divisiones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
            .addComponent(botonTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        intruccionesPrincipalLayout.setVerticalGroup(
            intruccionesPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intruccionesPrincipalLayout.createSequentialGroup()
                .addComponent(botonTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(divisiones, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout instruccionesLayout = new javax.swing.GroupLayout(instrucciones.getContentPane());
        instrucciones.getContentPane().setLayout(instruccionesLayout);
        instruccionesLayout.setHorizontalGroup(
            instruccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(intruccionesPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        instruccionesLayout.setVerticalGroup(
            instruccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(intruccionesPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zombie Defense");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"));
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(627, 394));

        panelCompleto.setBackground(new java.awt.Color(0, 51, 0));
        panelCompleto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelCompleto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelCompletoMousePressed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        logo.setName(""); // NOI18N
        logo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                logoMouseDragged(evt);
            }
        });
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoMousePressed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 30, 0));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnPlay.setBackground(new java.awt.Color(0, 30, 0));
        btnPlay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(255, 255, 255));
        btnPlay.setText("Play");
        btnPlay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnConfig.setBackground(new java.awt.Color(0, 30, 0));
        btnConfig.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnConfig.setForeground(new java.awt.Color(255, 255, 255));
        btnConfig.setText("Configuracion");
        btnConfig.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });

        btnInstrucciones.setBackground(new java.awt.Color(0, 30, 0));
        btnInstrucciones.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnInstrucciones.setForeground(new java.awt.Color(255, 255, 255));
        btnInstrucciones.setText("Instrucciones");
        btnInstrucciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstruccionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCompletoLayout = new javax.swing.GroupLayout(panelCompleto);
        panelCompleto.setLayout(panelCompletoLayout);
        panelCompletoLayout.setHorizontalGroup(
            panelCompletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompletoLayout.createSequentialGroup()
                .addGroup(panelCompletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCompletoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCompletoLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(logo)
                .addGroup(panelCompletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCompletoLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCompletoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        panelCompletoLayout.setVerticalGroup(
            panelCompletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompletoLayout.createSequentialGroup()
                .addGroup(panelCompletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCompletoLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(logo))
                    .addGroup(panelCompletoLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnPlay)
                        .addGap(50, 50, 50)
                        .addComponent(btnConfig))
                    .addGroup(panelCompletoLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnSalir)
                        .addGap(50, 50, 50)
                        .addComponent(btnInstrucciones)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        getContentPane().add(panelCompleto, java.awt.BorderLayout.CENTER);
        panelCompleto.getAccessibleContext().setAccessibleName("");
        panelCompleto.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        VentanaConfiguracion configuracion = new VentanaConfiguracion();
        configuracion.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnConfigActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstruccionesActionPerformed
        instrucciones.setLocationRelativeTo(null);
        instrucciones.setVisible(true);
        setVisible(false);
       
    }//GEN-LAST:event_btnInstruccionesActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        btnCerrar.setBackground(new Color(0,51,0));
        instrucciones.setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void panelCompletoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCompletoMousePressed
        
    }//GEN-LAST:event_panelCompletoMousePressed

    private void logoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_logoMousePressed

    private void logoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, 
        this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_logoMouseDragged

    private void lblTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_lblTituloMousePressed

    private void lblTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloMouseDragged
        instrucciones.setLocation(instrucciones.getLocation().x + evt.getX() - x,
        instrucciones.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_lblTituloMouseDragged

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        juego = new Juego(mapa, p1, p2, p3);
        setVisible(false);
        juego.iniciar();
    }//GEN-LAST:event_btnPlayActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel botonTitle;
    public javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnConfig;
    public javax.swing.JButton btnInstrucciones;
    public javax.swing.JButton btnPlay;
    public javax.swing.JButton btnSalir;
    public javax.swing.JTabbedPane divisiones;
    public javax.swing.JDialog instrucciones;
    public javax.swing.JPanel intruccionesPrincipal;
    public javax.swing.JLabel lblTitulo;
    public javax.swing.JLabel logo;
    public javax.swing.JScrollPane paneInformacion;
    public javax.swing.JScrollPane paneInstrucciones;
    public javax.swing.JPanel panelCompleto;
    public javax.swing.JTextArea txtInformacion;
    public javax.swing.JTextArea txtInstrucciones;
    // End of variables declaration//GEN-END:variables
    
    
}
