
package zombiedefense.mapa;

import javax.swing.JPanel;
import zombiedefense.Juego;
import static zombiedefense.VentanaPrincipal.juego;
import static zombiedefense.VentanaPrincipal.ventana;

public class PanelControl extends JPanel{

    
    public PanelControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        btnSalirMenu = new javax.swing.JButton();
        btnSalirJuego = new javax.swing.JButton();
        btnPausa = new javax.swing.JToggleButton();
        informacionPersonajes = new javax.swing.JTabbedPane();
        personaje1 = new javax.swing.JPanel();
        iconoP1 = new javax.swing.JLabel();
        itemsHabilidades = new javax.swing.JTabbedPane();
        panelItems = new javax.swing.JPanel();
        item1 = new javax.swing.JLabel();
        item2 = new javax.swing.JLabel();
        item3 = new javax.swing.JLabel();
        item4 = new javax.swing.JLabel();
        item5 = new javax.swing.JLabel();
        item6 = new javax.swing.JLabel();
        nameI1 = new javax.swing.JLabel();
        nameI2 = new javax.swing.JLabel();
        nameI3 = new javax.swing.JLabel();
        nameI4 = new javax.swing.JLabel();
        nameI5 = new javax.swing.JLabel();
        nameI6 = new javax.swing.JLabel();
        Habilidades = new javax.swing.JPanel();
        hab1 = new javax.swing.JLabel();
        hab2 = new javax.swing.JLabel();
        hab3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblAtaque8 = new javax.swing.JLabel();
        jProgressBar15 = new javax.swing.JProgressBar();
        lblAtaque9 = new javax.swing.JLabel();
        lblVida6 = new javax.swing.JLabel();
        jProgressBar16 = new javax.swing.JProgressBar();
        jProgressBar17 = new javax.swing.JProgressBar();
        personaje2 = new javax.swing.JPanel();
        iconoP4 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        panelItems1 = new javax.swing.JPanel();
        item7 = new javax.swing.JLabel();
        item8 = new javax.swing.JLabel();
        item9 = new javax.swing.JLabel();
        item10 = new javax.swing.JLabel();
        item11 = new javax.swing.JLabel();
        item12 = new javax.swing.JLabel();
        nameI7 = new javax.swing.JLabel();
        nameI8 = new javax.swing.JLabel();
        nameI9 = new javax.swing.JLabel();
        nameI10 = new javax.swing.JLabel();
        nameI11 = new javax.swing.JLabel();
        nameI12 = new javax.swing.JLabel();
        Habilidades1 = new javax.swing.JPanel();
        hab4 = new javax.swing.JLabel();
        hab5 = new javax.swing.JLabel();
        hab6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        lblVida5 = new javax.swing.JLabel();
        jProgressBar12 = new javax.swing.JProgressBar();
        lblAtaque6 = new javax.swing.JLabel();
        jProgressBar13 = new javax.swing.JProgressBar();
        lblAtaque7 = new javax.swing.JLabel();
        jProgressBar14 = new javax.swing.JProgressBar();
        personaje3 = new javax.swing.JPanel();
        iconoP6 = new javax.swing.JLabel();
        jProgressBar7 = new javax.swing.JProgressBar();
        lblVida3 = new javax.swing.JLabel();
        lblAtaque3 = new javax.swing.JLabel();
        jProgressBar8 = new javax.swing.JProgressBar();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        panelItems3 = new javax.swing.JPanel();
        item19 = new javax.swing.JLabel();
        item20 = new javax.swing.JLabel();
        item21 = new javax.swing.JLabel();
        item22 = new javax.swing.JLabel();
        item23 = new javax.swing.JLabel();
        item24 = new javax.swing.JLabel();
        nameI19 = new javax.swing.JLabel();
        nameI20 = new javax.swing.JLabel();
        nameI21 = new javax.swing.JLabel();
        nameI22 = new javax.swing.JLabel();
        nameI23 = new javax.swing.JLabel();
        nameI24 = new javax.swing.JLabel();
        Habilidades3 = new javax.swing.JPanel();
        hab10 = new javax.swing.JLabel();
        hab11 = new javax.swing.JLabel();
        hab12 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        jScrollPane17 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        lblAtaque5 = new javax.swing.JLabel();
        jProgressBar11 = new javax.swing.JProgressBar();

        setBackground(new java.awt.Color(0, 51, 0));
        setPreferredSize(new java.awt.Dimension(255, 768));

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("zombiedefense/mapa/Bundle"); // NOI18N
        titulo.setText(bundle.getString("PanelControl.titulo.text")); // NOI18N

        btnSalirMenu.setBackground(new java.awt.Color(0, 30, 0));
        btnSalirMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalirMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirMenu.setText(bundle.getString("PanelControl.btnSalirMenu.text")); // NOI18N
        btnSalirMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirMenuActionPerformed(evt);
            }
        });

        btnSalirJuego.setBackground(new java.awt.Color(0, 30, 0));
        btnSalirJuego.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalirJuego.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirJuego.setText(bundle.getString("PanelControl.btnSalirJuego.text")); // NOI18N
        btnSalirJuego.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalirJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirJuegoActionPerformed(evt);
            }
        });

        btnPausa.setBackground(new java.awt.Color(0, 30, 0));
        btnPausa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPausa.setForeground(new java.awt.Color(255, 255, 255));
        btnPausa.setText(bundle.getString("PanelControl.btnPausa.text")); // NOI18N
        btnPausa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausaActionPerformed(evt);
            }
        });

        iconoP1.setText(bundle.getString("PanelControl.iconoP1.text")); // NOI18N
        iconoP1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        iconoP1.setPreferredSize(new java.awt.Dimension(110, 110));

        panelItems.setBackground(new java.awt.Color(0, 41, 0));
        panelItems.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 30, 0)));

        item1.setText(bundle.getString("PanelControl.item1.text")); // NOI18N
        item1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        item1.setMaximumSize(new java.awt.Dimension(15, 15));
        item1.setPreferredSize(new java.awt.Dimension(50, 50));

        item2.setText(bundle.getString("PanelControl.item2.text")); // NOI18N
        item2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        item2.setMaximumSize(new java.awt.Dimension(15, 15));
        item2.setPreferredSize(new java.awt.Dimension(50, 50));

        item3.setText(bundle.getString("PanelControl.item3.text")); // NOI18N
        item3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        item3.setMaximumSize(new java.awt.Dimension(15, 15));
        item3.setPreferredSize(new java.awt.Dimension(50, 50));

        item4.setText(bundle.getString("PanelControl.item4.text")); // NOI18N
        item4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        item4.setMaximumSize(new java.awt.Dimension(15, 15));
        item4.setPreferredSize(new java.awt.Dimension(50, 50));

        item5.setText(bundle.getString("PanelControl.item5.text")); // NOI18N
        item5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        item5.setMaximumSize(new java.awt.Dimension(15, 15));
        item5.setPreferredSize(new java.awt.Dimension(50, 50));

        item6.setText(bundle.getString("PanelControl.item6.text")); // NOI18N
        item6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        item6.setMaximumSize(new java.awt.Dimension(15, 15));
        item6.setPreferredSize(new java.awt.Dimension(50, 50));

        nameI1.setText(bundle.getString("PanelControl.nameI1.text")); // NOI18N

        nameI2.setText(bundle.getString("PanelControl.nameI2.text")); // NOI18N

        nameI3.setText(bundle.getString("PanelControl.nameI3.text")); // NOI18N

        nameI4.setText(bundle.getString("PanelControl.nameI4.text")); // NOI18N

        nameI5.setText(bundle.getString("PanelControl.nameI5.text")); // NOI18N

        nameI6.setText(bundle.getString("PanelControl.nameI6.text")); // NOI18N

        javax.swing.GroupLayout panelItemsLayout = new javax.swing.GroupLayout(panelItems);
        panelItems.setLayout(panelItemsLayout);
        panelItemsLayout.setHorizontalGroup(
            panelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelItemsLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelItemsLayout.createSequentialGroup()
                        .addGroup(panelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelItemsLayout.createSequentialGroup()
                                .addComponent(item1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelItemsLayout.createSequentialGroup()
                                .addComponent(nameI1)
                                .addGap(29, 29, 29)))
                        .addGroup(panelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(item2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelItemsLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(nameI2)))
                        .addGap(18, 18, 18)
                        .addGroup(panelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelItemsLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(nameI3))
                            .addComponent(item3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelItemsLayout.createSequentialGroup()
                        .addGroup(panelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelItemsLayout.createSequentialGroup()
                                .addComponent(item4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(item6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelItemsLayout.createSequentialGroup()
                                .addComponent(nameI6)
                                .addGap(35, 35, 35)
                                .addComponent(nameI5)
                                .addGap(29, 29, 29)))
                        .addGroup(panelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelItemsLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(nameI4))
                            .addComponent(item5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelItemsLayout.setVerticalGroup(
            panelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelItemsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(panelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameI3)
                    .addComponent(nameI2)
                    .addComponent(nameI1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(panelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameI6)
                    .addComponent(nameI5)
                    .addComponent(nameI4))
                .addContainerGap())
        );

        itemsHabilidades.addTab(bundle.getString("PanelControl.panelItems.TabConstraints.tabTitle"), panelItems); // NOI18N

        Habilidades.setBackground(new java.awt.Color(0, 41, 0));
        Habilidades.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 30, 0)));

        hab1.setBackground(new java.awt.Color(255, 255, 255));
        hab1.setText(bundle.getString("PanelControl.hab1.text")); // NOI18N
        hab1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hab1.setPreferredSize(new java.awt.Dimension(40, 40));

        hab2.setText(bundle.getString("PanelControl.hab2.text")); // NOI18N
        hab2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hab2.setPreferredSize(new java.awt.Dimension(40, 40));

        hab3.setText(bundle.getString("PanelControl.hab3.text")); // NOI18N
        hab3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hab3.setPreferredSize(new java.awt.Dimension(40, 40));

        jScrollPane2.setBackground(new java.awt.Color(0, 51, 0));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 30, 0)));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 51, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jScrollPane3.setBackground(new java.awt.Color(0, 51, 0));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 30, 0)));
        jScrollPane3.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(0, 51, 0));
        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jScrollPane4.setBackground(new java.awt.Color(0, 51, 0));
        jScrollPane4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 30, 0)));
        jScrollPane4.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(0, 51, 0));
        jTextArea3.setColumns(20);
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        javax.swing.GroupLayout HabilidadesLayout = new javax.swing.GroupLayout(Habilidades);
        Habilidades.setLayout(HabilidadesLayout);
        HabilidadesLayout.setHorizontalGroup(
            HabilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HabilidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HabilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HabilidadesLayout.createSequentialGroup()
                        .addComponent(hab3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HabilidadesLayout.createSequentialGroup()
                        .addGroup(HabilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hab1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hab2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(HabilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        HabilidadesLayout.setVerticalGroup(
            HabilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HabilidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HabilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HabilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hab2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HabilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hab3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        itemsHabilidades.addTab(bundle.getString("PanelControl.Habilidades.TabConstraints.tabTitle"), Habilidades); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        jScrollPane5.setViewportView(jPanel1);

        lblAtaque8.setBackground(new java.awt.Color(255, 255, 255));
        lblAtaque8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAtaque8.setForeground(new java.awt.Color(255, 255, 255));
        lblAtaque8.setText(bundle.getString("PanelControl.lblAtaque8.text")); // NOI18N

        lblAtaque9.setBackground(new java.awt.Color(255, 255, 255));
        lblAtaque9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAtaque9.setForeground(new java.awt.Color(255, 255, 255));
        lblAtaque9.setText(bundle.getString("PanelControl.lblAtaque9.text")); // NOI18N

        lblVida6.setBackground(new java.awt.Color(255, 255, 255));
        lblVida6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblVida6.setForeground(new java.awt.Color(255, 255, 255));
        lblVida6.setText(bundle.getString("PanelControl.lblVida6.text")); // NOI18N

        javax.swing.GroupLayout personaje1Layout = new javax.swing.GroupLayout(personaje1);
        personaje1.setLayout(personaje1Layout);
        personaje1Layout.setHorizontalGroup(
            personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personaje1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(itemsHabilidades, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personaje1Layout.createSequentialGroup()
                        .addComponent(iconoP1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar15, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar17, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar16, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(personaje1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lblVida6))
                            .addGroup(personaje1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lblAtaque8))
                            .addGroup(personaje1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblAtaque9)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        personaje1Layout.setVerticalGroup(
            personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personaje1Layout.createSequentialGroup()
                .addGroup(personaje1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personaje1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconoP1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(personaje1Layout.createSequentialGroup()
                        .addComponent(lblVida6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar17, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAtaque8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar15, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAtaque9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jProgressBar16, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemsHabilidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        informacionPersonajes.addTab(bundle.getString("PanelControl.personaje1.TabConstraints.tabTitle"), personaje1); // NOI18N

        iconoP4.setText(bundle.getString("PanelControl.iconoP4.text")); // NOI18N
        iconoP4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        iconoP4.setPreferredSize(new java.awt.Dimension(110, 110));

        panelItems1.setBackground(new java.awt.Color(0, 41, 0));
        panelItems1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 30, 0)));

        item7.setText(bundle.getString("PanelControl.item7.text")); // NOI18N
        item7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        item7.setMaximumSize(new java.awt.Dimension(15, 15));
        item7.setPreferredSize(new java.awt.Dimension(50, 50));

        item8.setText(bundle.getString("PanelControl.item8.text")); // NOI18N
        item8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        item8.setMaximumSize(new java.awt.Dimension(15, 15));
        item8.setPreferredSize(new java.awt.Dimension(50, 50));

        item9.setText(bundle.getString("PanelControl.item9.text")); // NOI18N
        item9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        item9.setMaximumSize(new java.awt.Dimension(15, 15));
        item9.setPreferredSize(new java.awt.Dimension(50, 50));

        item10.setText(bundle.getString("PanelControl.item10.text")); // NOI18N
        item10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        item10.setMaximumSize(new java.awt.Dimension(15, 15));
        item10.setPreferredSize(new java.awt.Dimension(50, 50));

        item11.setText(bundle.getString("PanelControl.item11.text")); // NOI18N
        item11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        item11.setMaximumSize(new java.awt.Dimension(15, 15));
        item11.setPreferredSize(new java.awt.Dimension(50, 50));

        item12.setText(bundle.getString("PanelControl.item12.text")); // NOI18N
        item12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        item12.setMaximumSize(new java.awt.Dimension(15, 15));
        item12.setPreferredSize(new java.awt.Dimension(50, 50));

        nameI7.setText(bundle.getString("PanelControl.nameI7.text")); // NOI18N

        nameI8.setText(bundle.getString("PanelControl.nameI8.text")); // NOI18N

        nameI9.setText(bundle.getString("PanelControl.nameI9.text")); // NOI18N

        nameI10.setText(bundle.getString("PanelControl.nameI10.text")); // NOI18N

        nameI11.setText(bundle.getString("PanelControl.nameI11.text")); // NOI18N

        nameI12.setText(bundle.getString("PanelControl.nameI12.text")); // NOI18N

        javax.swing.GroupLayout panelItems1Layout = new javax.swing.GroupLayout(panelItems1);
        panelItems1.setLayout(panelItems1Layout);
        panelItems1Layout.setHorizontalGroup(
            panelItems1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelItems1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelItems1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelItems1Layout.createSequentialGroup()
                        .addGroup(panelItems1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelItems1Layout.createSequentialGroup()
                                .addComponent(item7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelItems1Layout.createSequentialGroup()
                                .addComponent(nameI7)
                                .addGap(29, 29, 29)))
                        .addGroup(panelItems1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(item8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelItems1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(nameI8)))
                        .addGap(18, 18, 18)
                        .addGroup(panelItems1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelItems1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(nameI9))
                            .addComponent(item9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelItems1Layout.createSequentialGroup()
                        .addGroup(panelItems1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelItems1Layout.createSequentialGroup()
                                .addComponent(item10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(item12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelItems1Layout.createSequentialGroup()
                                .addComponent(nameI12)
                                .addGap(35, 35, 35)
                                .addComponent(nameI11)
                                .addGap(29, 29, 29)))
                        .addGroup(panelItems1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelItems1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(nameI10))
                            .addComponent(item11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelItems1Layout.setVerticalGroup(
            panelItems1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelItems1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelItems1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(panelItems1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameI9)
                    .addComponent(nameI8)
                    .addComponent(nameI7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(panelItems1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelItems1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameI12)
                    .addComponent(nameI11)
                    .addComponent(nameI10))
                .addContainerGap())
        );

        jTabbedPane2.addTab(bundle.getString("PanelControl.panelItems1.TabConstraints.tabTitle"), panelItems1); // NOI18N

        Habilidades1.setBackground(new java.awt.Color(0, 41, 0));
        Habilidades1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 30, 0)));

        hab4.setBackground(new java.awt.Color(255, 255, 255));
        hab4.setText(bundle.getString("PanelControl.hab4.text")); // NOI18N
        hab4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hab4.setPreferredSize(new java.awt.Dimension(40, 40));

        hab5.setText(bundle.getString("PanelControl.hab5.text")); // NOI18N
        hab5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hab5.setPreferredSize(new java.awt.Dimension(40, 40));

        hab6.setText(bundle.getString("PanelControl.hab6.text")); // NOI18N
        hab6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hab6.setPreferredSize(new java.awt.Dimension(40, 40));

        jScrollPane6.setBackground(new java.awt.Color(0, 51, 0));
        jScrollPane6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 30, 0)));
        jScrollPane6.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(0, 51, 0));
        jTextArea4.setColumns(20);
        jTextArea4.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea4.setRows(5);
        jScrollPane6.setViewportView(jTextArea4);

        jScrollPane7.setBackground(new java.awt.Color(0, 51, 0));
        jScrollPane7.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 30, 0)));
        jScrollPane7.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(new java.awt.Color(0, 51, 0));
        jTextArea5.setColumns(20);
        jTextArea5.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea5.setRows(5);
        jScrollPane7.setViewportView(jTextArea5);

        jScrollPane8.setBackground(new java.awt.Color(0, 51, 0));
        jScrollPane8.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 30, 0)));
        jScrollPane8.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea6.setEditable(false);
        jTextArea6.setBackground(new java.awt.Color(0, 51, 0));
        jTextArea6.setColumns(20);
        jTextArea6.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea6.setRows(5);
        jScrollPane8.setViewportView(jTextArea6);

        javax.swing.GroupLayout Habilidades1Layout = new javax.swing.GroupLayout(Habilidades1);
        Habilidades1.setLayout(Habilidades1Layout);
        Habilidades1Layout.setHorizontalGroup(
            Habilidades1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Habilidades1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Habilidades1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Habilidades1Layout.createSequentialGroup()
                        .addComponent(hab6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Habilidades1Layout.createSequentialGroup()
                        .addGroup(Habilidades1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hab4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hab5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Habilidades1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        Habilidades1Layout.setVerticalGroup(
            Habilidades1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Habilidades1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Habilidades1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Habilidades1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hab5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Habilidades1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hab6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab(bundle.getString("PanelControl.Habilidades1.TabConstraints.tabTitle"), Habilidades1); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        jScrollPane9.setViewportView(jPanel2);

        lblVida5.setBackground(new java.awt.Color(255, 255, 255));
        lblVida5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblVida5.setForeground(new java.awt.Color(255, 255, 255));
        lblVida5.setText(bundle.getString("PanelControl.lblVida5.text")); // NOI18N

        lblAtaque6.setBackground(new java.awt.Color(255, 255, 255));
        lblAtaque6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAtaque6.setForeground(new java.awt.Color(255, 255, 255));
        lblAtaque6.setText(bundle.getString("PanelControl.lblAtaque6.text")); // NOI18N

        lblAtaque7.setBackground(new java.awt.Color(255, 255, 255));
        lblAtaque7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAtaque7.setForeground(new java.awt.Color(255, 255, 255));
        lblAtaque7.setText(bundle.getString("PanelControl.lblAtaque7.text")); // NOI18N

        javax.swing.GroupLayout personaje2Layout = new javax.swing.GroupLayout(personaje2);
        personaje2.setLayout(personaje2Layout);
        personaje2Layout.setHorizontalGroup(
            personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personaje2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personaje2Layout.createSequentialGroup()
                        .addComponent(iconoP4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar13, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar12, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar14, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(personaje2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lblVida5))
                            .addGroup(personaje2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lblAtaque6))
                            .addGroup(personaje2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblAtaque7)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        personaje2Layout.setVerticalGroup(
            personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personaje2Layout.createSequentialGroup()
                .addGroup(personaje2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personaje2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconoP4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(personaje2Layout.createSequentialGroup()
                        .addComponent(lblVida5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar12, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAtaque6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar13, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAtaque7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jProgressBar14, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        informacionPersonajes.addTab(bundle.getString("PanelControl.personaje2.TabConstraints.tabTitle"), personaje2); // NOI18N

        iconoP6.setText(bundle.getString("PanelControl.iconoP6.text")); // NOI18N
        iconoP6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        iconoP6.setPreferredSize(new java.awt.Dimension(110, 110));

        lblVida3.setBackground(new java.awt.Color(255, 255, 255));
        lblVida3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblVida3.setForeground(new java.awt.Color(255, 255, 255));
        lblVida3.setText(bundle.getString("PanelControl.lblVida3.text")); // NOI18N

        lblAtaque3.setBackground(new java.awt.Color(255, 255, 255));
        lblAtaque3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAtaque3.setForeground(new java.awt.Color(255, 255, 255));
        lblAtaque3.setText(bundle.getString("PanelControl.lblAtaque3.text")); // NOI18N

        panelItems3.setBackground(new java.awt.Color(0, 41, 0));
        panelItems3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 30, 0)));

        item19.setText(bundle.getString("PanelControl.item19.text")); // NOI18N
        item19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        item19.setMaximumSize(new java.awt.Dimension(15, 15));
        item19.setPreferredSize(new java.awt.Dimension(50, 50));

        item20.setText(bundle.getString("PanelControl.item20.text")); // NOI18N
        item20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        item20.setMaximumSize(new java.awt.Dimension(15, 15));
        item20.setPreferredSize(new java.awt.Dimension(50, 50));

        item21.setText(bundle.getString("PanelControl.item21.text")); // NOI18N
        item21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        item21.setMaximumSize(new java.awt.Dimension(15, 15));
        item21.setPreferredSize(new java.awt.Dimension(50, 50));

        item22.setText(bundle.getString("PanelControl.item22.text")); // NOI18N
        item22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        item22.setMaximumSize(new java.awt.Dimension(15, 15));
        item22.setPreferredSize(new java.awt.Dimension(50, 50));

        item23.setText(bundle.getString("PanelControl.item23.text")); // NOI18N
        item23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        item23.setMaximumSize(new java.awt.Dimension(15, 15));
        item23.setPreferredSize(new java.awt.Dimension(50, 50));

        item24.setText(bundle.getString("PanelControl.item24.text")); // NOI18N
        item24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        item24.setMaximumSize(new java.awt.Dimension(15, 15));
        item24.setPreferredSize(new java.awt.Dimension(50, 50));

        nameI19.setText(bundle.getString("PanelControl.nameI19.text")); // NOI18N

        nameI20.setText(bundle.getString("PanelControl.nameI20.text")); // NOI18N

        nameI21.setText(bundle.getString("PanelControl.nameI21.text")); // NOI18N

        nameI22.setText(bundle.getString("PanelControl.nameI22.text")); // NOI18N

        nameI23.setText(bundle.getString("PanelControl.nameI23.text")); // NOI18N

        nameI24.setText(bundle.getString("PanelControl.nameI24.text")); // NOI18N

        javax.swing.GroupLayout panelItems3Layout = new javax.swing.GroupLayout(panelItems3);
        panelItems3.setLayout(panelItems3Layout);
        panelItems3Layout.setHorizontalGroup(
            panelItems3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelItems3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelItems3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelItems3Layout.createSequentialGroup()
                        .addGroup(panelItems3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelItems3Layout.createSequentialGroup()
                                .addComponent(item19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelItems3Layout.createSequentialGroup()
                                .addComponent(nameI19)
                                .addGap(29, 29, 29)))
                        .addGroup(panelItems3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(item20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelItems3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(nameI20)))
                        .addGap(18, 18, 18)
                        .addGroup(panelItems3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelItems3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(nameI21))
                            .addComponent(item21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelItems3Layout.createSequentialGroup()
                        .addGroup(panelItems3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelItems3Layout.createSequentialGroup()
                                .addComponent(item22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(item24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelItems3Layout.createSequentialGroup()
                                .addComponent(nameI24)
                                .addGap(35, 35, 35)
                                .addComponent(nameI23)
                                .addGap(29, 29, 29)))
                        .addGroup(panelItems3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelItems3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(nameI22))
                            .addComponent(item23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelItems3Layout.setVerticalGroup(
            panelItems3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelItems3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelItems3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(panelItems3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameI21)
                    .addComponent(nameI20)
                    .addComponent(nameI19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(panelItems3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelItems3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameI24)
                    .addComponent(nameI23)
                    .addComponent(nameI22))
                .addContainerGap())
        );

        jTabbedPane4.addTab(bundle.getString("PanelControl.panelItems3.TabConstraints.tabTitle"), panelItems3); // NOI18N

        Habilidades3.setBackground(new java.awt.Color(0, 41, 0));
        Habilidades3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 30, 0)));

        hab10.setBackground(new java.awt.Color(255, 255, 255));
        hab10.setText(bundle.getString("PanelControl.hab10.text")); // NOI18N
        hab10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hab10.setPreferredSize(new java.awt.Dimension(40, 40));

        hab11.setText(bundle.getString("PanelControl.hab11.text")); // NOI18N
        hab11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hab11.setPreferredSize(new java.awt.Dimension(40, 40));

        hab12.setText(bundle.getString("PanelControl.hab12.text")); // NOI18N
        hab12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hab12.setPreferredSize(new java.awt.Dimension(40, 40));

        jScrollPane14.setBackground(new java.awt.Color(0, 51, 0));
        jScrollPane14.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 30, 0)));
        jScrollPane14.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea10.setEditable(false);
        jTextArea10.setBackground(new java.awt.Color(0, 51, 0));
        jTextArea10.setColumns(20);
        jTextArea10.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea10.setRows(5);
        jScrollPane14.setViewportView(jTextArea10);

        jScrollPane15.setBackground(new java.awt.Color(0, 51, 0));
        jScrollPane15.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 30, 0)));
        jScrollPane15.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea11.setEditable(false);
        jTextArea11.setBackground(new java.awt.Color(0, 51, 0));
        jTextArea11.setColumns(20);
        jTextArea11.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea11.setRows(5);
        jScrollPane15.setViewportView(jTextArea11);

        jScrollPane16.setBackground(new java.awt.Color(0, 51, 0));
        jScrollPane16.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 30, 0)));
        jScrollPane16.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea12.setEditable(false);
        jTextArea12.setBackground(new java.awt.Color(0, 51, 0));
        jTextArea12.setColumns(20);
        jTextArea12.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea12.setRows(5);
        jScrollPane16.setViewportView(jTextArea12);

        javax.swing.GroupLayout Habilidades3Layout = new javax.swing.GroupLayout(Habilidades3);
        Habilidades3.setLayout(Habilidades3Layout);
        Habilidades3Layout.setHorizontalGroup(
            Habilidades3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Habilidades3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Habilidades3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Habilidades3Layout.createSequentialGroup()
                        .addComponent(hab12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Habilidades3Layout.createSequentialGroup()
                        .addGroup(Habilidades3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hab10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hab11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Habilidades3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        Habilidades3Layout.setVerticalGroup(
            Habilidades3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Habilidades3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Habilidades3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hab10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Habilidades3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hab11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Habilidades3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hab12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab(bundle.getString("PanelControl.Habilidades3.TabConstraints.tabTitle"), Habilidades3); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        jScrollPane17.setViewportView(jPanel4);

        lblAtaque5.setBackground(new java.awt.Color(255, 255, 255));
        lblAtaque5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAtaque5.setForeground(new java.awt.Color(255, 255, 255));
        lblAtaque5.setText(bundle.getString("PanelControl.lblAtaque5.text")); // NOI18N

        javax.swing.GroupLayout personaje3Layout = new javax.swing.GroupLayout(personaje3);
        personaje3.setLayout(personaje3Layout);
        personaje3Layout.setHorizontalGroup(
            personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personaje3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personaje3Layout.createSequentialGroup()
                        .addComponent(iconoP6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personaje3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jProgressBar8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jProgressBar7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jProgressBar11, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(personaje3Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(lblVida3))
                            .addGroup(personaje3Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(lblAtaque3))
                            .addGroup(personaje3Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lblAtaque5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        personaje3Layout.setVerticalGroup(
            personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personaje3Layout.createSequentialGroup()
                .addGroup(personaje3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personaje3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconoP6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(personaje3Layout.createSequentialGroup()
                        .addComponent(lblVida3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar7, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAtaque3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar8, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAtaque5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jProgressBar11, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        informacionPersonajes.addTab(bundle.getString("PanelControl.personaje3.TabConstraints.tabTitle"), personaje3); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(informacionPersonajes)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPausa, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalirJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalirMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(informacionPersonajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPausa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalirJuego)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalirMenu)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Funcion del boton salir menu
     * Esta funcion cierra la ventana del juego, detiene el hilo que corre 
     * el juego y abre la ventana principal
     * @param evt 
     */
    private void btnSalirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMenuActionPerformed
        ventana.setVisible(true);
        juego.detener();
        juego.setVisible(false);
    }//GEN-LAST:event_btnSalirMenuActionPerformed
    /**
     * Funcion del boton salir juego
     * Este metodo cierra por completo el programa
     * @param evt 
     */
    private void btnSalirJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirJuegoActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirJuegoActionPerformed

    private void btnPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausaActionPerformed
        if (Juego.enFuncionamiento){
            juego.pausa();
            titulo.setText(Juego.NOMBRE + " || PAUSA "+  " || Tiempo: " + Juego.minutos + ":" + Juego.segundos);
            btnPausa.setBackground(new java.awt.Color(0, 30, 0));
            btnPausa.setText("Resumen");
        }
        else{
            juego.iniciar();
            btnPausa.setText("Pausa");
            btnPausa.setBackground(new java.awt.Color(0, 30, 0));
        }
    }//GEN-LAST:event_btnPausaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Habilidades;
    public javax.swing.JPanel Habilidades1;
    public javax.swing.JPanel Habilidades3;
    public javax.swing.JToggleButton btnPausa;
    public javax.swing.JButton btnSalirJuego;
    public javax.swing.JButton btnSalirMenu;
    public javax.swing.JLabel hab1;
    public javax.swing.JLabel hab10;
    public javax.swing.JLabel hab11;
    public javax.swing.JLabel hab12;
    public javax.swing.JLabel hab2;
    public javax.swing.JLabel hab3;
    public javax.swing.JLabel hab4;
    public javax.swing.JLabel hab5;
    public javax.swing.JLabel hab6;
    public javax.swing.JLabel iconoP1;
    public javax.swing.JLabel iconoP4;
    public javax.swing.JLabel iconoP6;
    public javax.swing.JTabbedPane informacionPersonajes;
    public javax.swing.JLabel item1;
    public javax.swing.JLabel item10;
    public javax.swing.JLabel item11;
    public javax.swing.JLabel item12;
    public javax.swing.JLabel item19;
    public javax.swing.JLabel item2;
    public javax.swing.JLabel item20;
    public javax.swing.JLabel item21;
    public javax.swing.JLabel item22;
    public javax.swing.JLabel item23;
    public javax.swing.JLabel item24;
    public javax.swing.JLabel item3;
    public javax.swing.JLabel item4;
    public javax.swing.JLabel item5;
    public javax.swing.JLabel item6;
    public javax.swing.JLabel item7;
    public javax.swing.JLabel item8;
    public javax.swing.JLabel item9;
    public javax.swing.JTabbedPane itemsHabilidades;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JProgressBar jProgressBar11;
    public javax.swing.JProgressBar jProgressBar12;
    public javax.swing.JProgressBar jProgressBar13;
    public javax.swing.JProgressBar jProgressBar14;
    public javax.swing.JProgressBar jProgressBar15;
    public javax.swing.JProgressBar jProgressBar16;
    public javax.swing.JProgressBar jProgressBar17;
    public javax.swing.JProgressBar jProgressBar7;
    public javax.swing.JProgressBar jProgressBar8;
    public javax.swing.JScrollPane jScrollPane14;
    public javax.swing.JScrollPane jScrollPane15;
    public javax.swing.JScrollPane jScrollPane16;
    public javax.swing.JScrollPane jScrollPane17;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JTabbedPane jTabbedPane2;
    public javax.swing.JTabbedPane jTabbedPane4;
    public javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextArea jTextArea10;
    public javax.swing.JTextArea jTextArea11;
    public javax.swing.JTextArea jTextArea12;
    public javax.swing.JTextArea jTextArea2;
    public javax.swing.JTextArea jTextArea3;
    public javax.swing.JTextArea jTextArea4;
    public javax.swing.JTextArea jTextArea5;
    public javax.swing.JTextArea jTextArea6;
    public javax.swing.JLabel lblAtaque3;
    public javax.swing.JLabel lblAtaque5;
    public javax.swing.JLabel lblAtaque6;
    public javax.swing.JLabel lblAtaque7;
    public javax.swing.JLabel lblAtaque8;
    public javax.swing.JLabel lblAtaque9;
    public javax.swing.JLabel lblVida3;
    public javax.swing.JLabel lblVida5;
    public javax.swing.JLabel lblVida6;
    public javax.swing.JLabel nameI1;
    public javax.swing.JLabel nameI10;
    public javax.swing.JLabel nameI11;
    public javax.swing.JLabel nameI12;
    public javax.swing.JLabel nameI19;
    public javax.swing.JLabel nameI2;
    public javax.swing.JLabel nameI20;
    public javax.swing.JLabel nameI21;
    public javax.swing.JLabel nameI22;
    public javax.swing.JLabel nameI23;
    public javax.swing.JLabel nameI24;
    public javax.swing.JLabel nameI3;
    public javax.swing.JLabel nameI4;
    public javax.swing.JLabel nameI5;
    public javax.swing.JLabel nameI6;
    public javax.swing.JLabel nameI7;
    public javax.swing.JLabel nameI8;
    public javax.swing.JLabel nameI9;
    public javax.swing.JPanel panelItems;
    public javax.swing.JPanel panelItems1;
    public javax.swing.JPanel panelItems3;
    public javax.swing.JPanel personaje1;
    public javax.swing.JPanel personaje2;
    public javax.swing.JPanel personaje3;
    public javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

}
